defaults/main.yaml
tasks/crio.yaml
templates/microshift.repo.j2

The new Microshift version has packages also for RHEL 9 base system.

Bump Microshift version to 4.13

---

defaults/main.yaml
tasks/crio.yaml
templates/microshift.repo.j2

Some images might not be accessible without setting "overwrite_container_policy" variable to  true.

Revert "Bump Microshift version to 4.13"

---

tasks/crio.yaml
templates/microshift.repo.j2

The new Microshift version has more pod security enhancements, that can break the operator deployment.
Until new patches that fixes the deployment are not merged, let's add back capability to version 4.12 to continue develop the operator (sf-operator).

Add capability to use version 4.12

---

defaults/main.yaml
tasks/dnsmasq.yaml
tasks/main.yaml

The DNSMasq service would be helpful especially for developers, that would try to make a query for new deployed service. It does not need to add each time proper entry into the /etc/hosts to resolve the domain.

Add feature to install DNSMasq service

---

tasks/dnsmasq.yaml

The handlers should be triggered before OLM setup will be executed.

Flush handlers afer dnsmasq is configured

---

tasks/dnsmasq.yaml

The 99-cloud-init.conf file if exists is overwriting values that are set by the Microshift service. It also makes that the /etc/NetworkManager/dnsmasq.d/dnsmasq.conf file is ignored.

Comment 99-cloud-init.conf file if exists

---

tasks/dnsmasq.yaml

Listen dnsmasq also on local ip address
This change will enable on dnsmasq listening in NetworkManager also on the
on local ip address of the host. It would be useful, when
someone would like to provide local domains, that can be resolved by the
dnsmasq service inside the OpenShift cluster.
For example, if someone would like to enable resolving hostname:
logserver.sftests.com inside the pod, not by using the Kubernetes like
domain name resolution, it is needed to add a new entry into the dns-default
configmap and the dns query will be forwarded to the dnsmasq on the
host.
Example:
oc edit configmap -n openshift-dns  dns-default
(...)
logserver.sftest.com {
errors
cache 30
forward . <server local ip address that is in dnsmasq.conf>
}
Then  restart services
oc -n openshift-dns rollout …

Listen dnsmasq also on local ip address

---

files/start-lvm.sh
tasks/openshift-storage.yaml
templates/microshift-loop-device.service.j2

After the reboot, the volume group is available:
$ vgdisplay
--- Volume group ---
VG Name               rhel
(...)
and the volumes are also available:
$ lvdisplay
--- Logical volume ---
LV Path                /dev/rhel/37449bb2-9190-4846-8ec1-562361e0fdbc
LV Name                37449bb2-9190-4846-8ec1-562361e0fdbc
(...)
but the directory /dev/rhel is not available, so by checking:
$ lvscan
inactive          '/dev/rhel/37449bb2-9190-4846-8ec1-562361e0fdbc' [1,00 GiB] inherit
inactive          '/dev/rhel/48917243-f3e8-46b5-be4d-8b40b5e0a8ec' [1,00 GiB] inherit
(...)
shows that all volumes are inactive state.
By iterating on all inactive volumes and execute command: vchange -ay <volume>
starts the volume mapping and the /dev/rhel is available. After a while, all pods that uses pv are …

Set lvm volumes to be active after reboot

---

defaults/main.yaml
handlers/main.yaml
tasks/coredns.yaml
tasks/dnsmasq.yaml
tasks/main.yaml
templates/corefile.yaml

That feature will be mostly used by the CI for simulating the external domains that exists normaly in the Internet.
For example, if domain '.sftests.com' have many subdomains and not each domain is registered domain in the Openshift cluster and the domain is just for test (not registered in any DNS authority) it will fail name resolution inside the pod with an error:
"curl: (6) Could not resolve host: test.sftests.com"
In that case, we are adding custom domain inside the codedns configuration configmap, which will forward the DNS queries made for that domain to the dnsmasq, which is installed on the host. The dnsmasq (which is started by NetworkManager) have proper entries to resolve the domain.

Add support to forward external domains DNS queries to dnsmasq

---

defaults/main.yaml
handlers/main.yaml
tasks/coredns.yaml
templates/reconfigure-coredns.sh.j2

Adding the new entry into the CoreDNS configmap should be done by using kubectl patch or replace instead of dumping the configuration, modify, remove not conflicting entries and apply resource to the cluster.

Add forwarder into the coredns configmap with replace

---

tasks/dnsmasq.yaml

When there was many nameserver entries available in the /etc/resolv.conf file, the lineinfile module was adding the dnsmasq entry before last match, not before first one.

Set dnsmasq nameserver as first nameserver in /etc/resolv.conf

---

tasks/dnsmasq.yaml

This change enables resolving `microshift.dev` from inside the cluster to the correct ip address (instead of getting localhost).

Set the fqdn to the ansible_default_ipv4

---

tasks/wait-for-microshift.yaml

From time to time we spotted that the wait-for-microshift.sh script fails from unknown reason.
This commit will help to find broken resource.

Print all resources when wait-for-microshift script fails

---

tasks/wait-for-microshift.yaml

The previous commit [1] is not ignoring errors, when the script fails.
[1] https://github.com/openstack-k8s-operators/ansible-microshift-role/pull/39

Check once again resource state after fail

---

defaults/main.yaml
tasks/etcd_ramdisk.yaml
tasks/main.yaml

That feature might help in the CI gates, when the host storage is not so fast.

Add experimental feature: mount etcd to ramdisk

---

tasks/crio.yaml

This change attempts to reduce failures such as:
TASK [ansible-microshift-role : Use only ipv4 - new Microshift] ****************
fatal: [microshift]: FAILED! => {"changed": false, "dest": "/etc/cni/net.d/100-crio-bridge.conf", "elapsed": 10, "msg": "Connection failure: The read operation timed out", "url": "https://raw.githubusercontent.com/cri-o/cri-o/v1.26.4/contrib/cni/11-crio-ipv4-bridge.conflist"}

crio.yaml - add retries/delay to get_url task

---

defaults/main.yaml

The cloudprovider_dns list should be empty.

Set empty list for cloudprovider_dns var

---

tasks/dnsmasq.yaml

The random function in Ansible is raising an error:
Cannot choose from an empty sequence
when the cloudprovider_dns is empty list.

Add workaround for random DNS when cloudprovider_dns is empty

---

tasks/microshift.yaml

It fixes the following warning:
```
[WARNING]: conditional statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: {{
```

Remove Jinja2 Templating Delimiters from Conditional Statement

---

handlers/main.yaml
tasks/dnsmasq.yaml

There is not need to install dnsmasq to provide same functionality as NetworkManager plugin do.

Drop dnsmasq service and use dnsmasq NetworkManager plugin

---

handlers/main.yaml
tasks/dnsmasq.yaml

The plugin requires to install dnsmasq package, due it will raise an error:
dns-mgr: init: dns=dnsmasq,systemd-resolved rc-manager=unmanaged, plugin=dnsmasq
dns-mgr: update-dns: plugin dnsmasq update failed: could not find dnsmasq binary

Install dnsmasq even when NetworkManager dnsmasq plugin enabled

---

defaults/main.yaml
tasks/openshift-storage.yaml

When a vg exists with vg_name exists it's not needed to create a sparse file. This change ensure an existing vg will be used

openshift-storage: Add check to not create vg if it exists

---

defaults/main.yaml
files/wait-for-microshift.sh
tasks/openshift-storage.yaml

This feature should be avoided as openshift-storage is the supported storage operator of Microshift.
This role provides the capability to setup a "rhel" LVM VG via a file mounted as a loop device. This integrates well with openshift-storage.
There is no clear usecase for the openshift-storage deletion.

Remove openshift-storage deletion feature

---

files/crio-bridge.conf
tasks/crio.yaml

This current method currenlty fails because the detected version is not avaible as a git tag on github.com.
TASK [/home/zuul-worker/ansible-microshift-role : Use only ipv4 - new Microshift] ***
fatal: [microshift]: FAILED! => {"changed": false, "dest": "/etc/cni/net.d/100-crio-bridge.conf", "elapsed": 0, "msg": "Request failed", "response": "HTTP Error 404: Not Found", "status_code": 404, "url": "https://raw.githubusercontent.com/cri-o/cri-o/v1.26.5/contrib/cni/11-crio-ipv4-bridge.conflist"}
This change simplifies the installation by provisionning the file directly in the role.

Use preprovisionned file for crio bridge

---

files/wait-for-microshift.sh

From time to time, the script wait-for-microshift.sh is failing because it is waiting for topolvm to be ready. It stuck on some point. Let's print such information, that might be useful for administrator to see where is an error.

Print storage information when wait for microshift script fails

---

templates/microshift.repo.j2

This commit is more a cosmetic change, because packages for few releases are same in both location - ocp and ocp-dev-preview, but it might happen, that there would be different version there. To avoid situation, that we would be able to install preview version, let's change the repository url to official.

Change repository directory

---

tasks/openshift-storage.yaml

In this commit, the tasks responsible for creating the loop device setup and disk creation are moved to earlier stage.
Also added tasks, that ensure if volume group, logical volume and loop device are created properly.

Change storage deployment order in Microshift setup; ensure vg is created

---

defaults/main.yaml
tasks/olm.yaml

The ansible is failing when tasks responsible for olm are triggered. Also changed a place for the binary: operator-sdk to better place (that binary might be useful in the future).

Fix OLM installation; remove repo_dir var; move operator-sdk to other dir

---

tasks/microshift.yaml

This commit is adding more base names to avoid situation, when the .kube/config file server is changed to other name, so the cert would be not valid.
Also changed kubeconfig file path to new one, that includes cert that belongs to provided fqdn.

Change kubeconfig path

---

tasks/main.yaml

The vg should be available before the MicroShift start. It will take less time to finish the deployment.

Create vg and lvm before MicroShift starts

---

defaults/main.yaml

It seems that in the new MicroShift version, the volume group (vg) name has changed and the default value is not "rhel" as it was. Even when we set the value to "rhel" to avoid situation, that on some hosts when we perform an upgrade we can loose data, the MicroShift is also creating vg with name "sc".

Add lvm information for storageclass

---

defaults/main.yaml

The cert should be extended to additional informations.
Also instead of setting the domain in the DNSMasq, we can set it in
MicroShift config.

Add baseDomain name and subjectAltName that is pointing to host ip address

---

tasks/microshift.yaml

The openvswitch3.1 is required by the microshift-networking package. The package has been updated in the MicroShift deps repository. Until the package is not back there, let's try to use CentOS NFV package.

Add workaround to install Open vSwitch in version 3.1

---

tasks/microshift.yaml

The ansible_user var is a special connection variable and is less likely to be set than ansible_user_dir and ansible_user_id.

use ansible_user_dir and ansible_user_id instead of ansible_user

---

tasks/microshift.yaml

The new MicroShift service (>4.14) can not start, because it is raising an error:
version.go:240] "START reading version file"
version.go:243] "FAIL reading version file" err="version file for MicroShift data does not exist"
version.go:127] "MicroShift data directory exists, but doesn't contain version file - assuming 4.13.0 and proceeding with versio>
version.go:54] "END getting versions" exec="4.16.0" data="4.13.0"
version.go:59] "START version compatibility checks"
This commit is adding the version file, so there is no need to install older MicroShift version.

Add version file if it does not exists

---

tasks/microshift.yaml

Normally the dir should be created by the rpm package, but in the CI, it is complaying, that the dir is missing (not all the time).

Ensure the /var/lib/microshift dir exists

---

defaults/main.yaml

The MicroShift 4.16 is marked as LTS release [1][2].
[1] https://docs.redhat.com/en/documentation/red_hat_build_of_microshift/4.16/html-single/installing/index#microshift-install-system-requirements_microshift-install-rpm
[2] https://access.redhat.com/product-life-cycles

Bump default MicroShift version to 4.16; update OperatorSDK to 1.36.1

---

tasks/main.yaml
tasks/microshift.yaml

Some "when" clauses check the os version by the value of Rhel instead of RedHat.

Change ansible_distribution from rhel to redhat

---

defaults/main.yaml
tasks/main.yaml

On some host, it might be running old MicroShift installation, which should not be updated directly to newest version.
To disable enabling RHEL subscription, set enable_rhocp_subscription variable to false.

Add enable_rhocp_subscription variable to disable RHEL subscription

---

tasks/main.yaml

That feature might be helpful for some deployments if on other hosts previous solution was used (without subscription).

Setup MicroShift old way even on RHEL system

---

tasks/microshift.yaml

The condition was already done in commit [1][2] to the main task file, but it was not added into the microshift task file.
[1] https://github.com/openstack-k8s-operators/ansible-microshift-role/pull/86
[2] https://github.com/openstack-k8s-operators/ansible-microshift-role/pull/87

Add conditions to install Microshift without subscription

---

defaults/main.yaml

When the volume group size is too small, setting spare-gb to 0 can lead to scheduling errors, such as:
0/1 nodes are available: 1 node(s) did not have enough free storage.
preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.
This change might cause issues with dynamic volume provisioning due to insufficient spare space. For more information on the impact of spare-gb, see documentation at [1].
[1] https://github.com/topolvm/topolvm/blob/main/docs/proposals/lvcreate-option-on-storageclass.md

Set spare-gb parameter to 0

---

defaults/main.yaml

The CI tests in sf-operator project will use hostAliases [1][2], so the workaround for discovering local domains are not needed.
[1] https://kubernetes.io/docs/tasks/network/customize-hosts-file-for-pods/
[2] https://softwarefactory-project.io/r/c/software-factory/sf-operator/+/32944

Disable dnsmasq

---

tasks/pre.yaml

This change removes unused dependencies (which is problematic on RHEL-9.4).

Remove golang installation
